services:
  - type: web
    name: seth-jabagat-portfolio
    runtime: docker
    plan: free
    region: singapore
    repo: https://github.com/gsi78eywh/csharp-portfolio
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /health
